export const DISCLAIMER_HEADLINE = "Before we get started";

export const DISCLAIMER_BODY = `Magis provides fitness programming based on the information you provide. Your workouts are fitness suggestions — not medical advice, and not a substitute for guidance from a qualified healthcare professional.

Before beginning any new exercise program, especially if you have existing health conditions, injuries, or concerns, we recommend consulting a qualified healthcare professional.

By continuing, you confirm that you understand Magis is a fitness tool, not a medical service, and that you take responsibility for training within your own limits.`;

export const DECLINE_MESSAGE =
  "That's okay. You won't be able to access your workouts without accepting these terms. You can review and accept them at any time from your profile settings.";

export const ACCEPT_LABEL = "I understand — let's go";
export const DECLINE_LABEL = "I'd rather not";

export const LOCALSTORAGE_KEY = "magis_disclaimer_accepted";

export const PARQ_PRIVACY_NOTICE =
  "Your health information is stored securely and used only to personalise your fitness programming. It is never shared with third parties.";

export const AI_DISCLAIMER_TEXT =
  "This is a fitness suggestion, not medical advice. If you have health concerns, consult a qualified healthcare professional.";

export const INJURY_ROUTING_CAVEAT =
  "For anything beyond minor muscle soreness, please seek a professional assessment before continuing to train the affected area.";

export const PROGRAM_FOOTER_COACHED =
  "Your program has been reviewed and approved by your coach. It is designed as a fitness guide — always train within your limits and consult a professional if you have health concerns.";

export const PROGRAM_FOOTER_AI_ONLY =
  "Generated by AI based on the information you provided. Always train within your limits and consult a professional if unsure.";
