-- ============================================================
-- Migration 007: Add Quads, Full Body, and Cardio exercises
-- Fills previously empty or missing muscle group categories.
-- 40 new exercises seeded in the same format as migration 005.
-- ============================================================

INSERT INTO public.exercises
  (created_by, name, muscle_group, secondary_muscles, equipment, movement_pattern, difficulty, instructions, is_custom, is_archived)
VALUES

-- ============================================================
-- QUADS (14 exercises)
-- ============================================================
('00000000-0000-0000-0000-000000000000', 'Back Squat', 'Quads', ARRAY['Glutes','Hamstrings','Core'], 'Barbell', 'squat', 'intermediate', 'Stand with the bar across your upper traps, feet shoulder-width apart. Brace your core, break at the hips and knees simultaneously, and descend until thighs are parallel to the floor. Drive through your heels to stand. Keep your chest tall and knees tracking over toes throughout.', false, false),
('00000000-0000-0000-0000-000000000000', 'Front Squat', 'Quads', ARRAY['Core','Glutes','Upper Back'], 'Barbell', 'squat', 'advanced', 'Rest the bar on your front delts with elbows high and parallel to the floor. Squat to depth with an upright torso — the front rack demands a more vertical shin angle, loading the quads heavily. Drive up through the floor, keeping elbows up throughout.', false, false),
('00000000-0000-0000-0000-000000000000', 'Leg Press', 'Quads', ARRAY['Glutes','Hamstrings'], 'Machine', 'squat', 'beginner', 'Sit in the leg press machine with feet shoulder-width on the platform. Lower the platform until your knees reach roughly 90 degrees, then press back to near-lockout. Do not lock out completely. Foot position affects emphasis: higher targets glutes, lower targets quads.', false, false),
('00000000-0000-0000-0000-000000000000', 'Hack Squat', 'Quads', ARRAY['Glutes','Hamstrings'], 'Machine', 'squat', 'intermediate', 'Load the hack squat machine and position your shoulders under the pads, feet shoulder-width on the platform. Lower under control until thighs are parallel, then press back up. The fixed path and back support allow you to focus on quad loading without balance demands.', false, false),
('00000000-0000-0000-0000-000000000000', 'Leg Extension', 'Quads', ARRAY[]::text[], 'Machine', 'isolation', 'beginner', 'Sit in the leg extension machine with the pad across your shins just above the ankles. Extend your legs to full lockout, squeeze the quads at the top for a beat, then lower under control. Avoid swinging or using momentum.', false, false),
('00000000-0000-0000-0000-000000000000', 'Lunge', 'Quads', ARRAY['Glutes','Hamstrings'], 'Dumbbell', 'lunge', 'beginner', 'Stand with dumbbells at your sides. Step one foot forward and lower your rear knee toward the floor, stopping just above it. Both knees should reach roughly 90 degrees. Drive through your front heel to return to standing. Alternate legs each rep or complete all reps on one side.', false, false),
('00000000-0000-0000-0000-000000000000', 'Walking Lunge', 'Quads', ARRAY['Glutes','Hamstrings','Core'], 'Dumbbell', 'lunge', 'beginner', 'Hold dumbbells at your sides. Step forward into a lunge and instead of returning to start, bring your rear foot forward to meet your front foot, then immediately step into the next rep. Continue travelling forward. Keep your torso upright and core braced throughout.', false, false),
('00000000-0000-0000-0000-000000000000', 'Reverse Lunge', 'Quads', ARRAY['Glutes','Hamstrings'], 'Dumbbell', 'lunge', 'beginner', 'Stand with dumbbells at your sides. Step one foot back and lower your rear knee toward the floor. This variation places less stress on the knee than a forward lunge and is easier to control. Drive through your front heel to return to standing.', false, false),
('00000000-0000-0000-0000-000000000000', 'Step-Up', 'Quads', ARRAY['Glutes','Hamstrings'], 'Dumbbell', 'lunge', 'beginner', 'Stand facing a box or bench holding dumbbells. Step one foot onto the box and drive through that heel to lift your body up. Bring the other foot up, then step back down in a controlled manner. Complete all reps on one side before switching, or alternate.', false, false),
('00000000-0000-0000-0000-000000000000', 'Box Squat', 'Quads', ARRAY['Glutes','Hamstrings','Core'], 'Barbell', 'squat', 'intermediate', 'Set a box at or just below parallel height. Squat back and down until you sit onto the box — do not relax or bounce. Maintain tension, then drive through the floor to stand. The box teaches depth consistency and eliminates the stretch-reflex, building raw strength.', false, false),
('00000000-0000-0000-0000-000000000000', 'Sissy Squat', 'Quads', ARRAY[]::text[], 'Bodyweight', 'isolation', 'advanced', 'Stand with feet close together. Lean back and allow your knees to travel forward over your toes as you lower your body toward the floor, keeping your hips extended. Lower until your knees nearly touch the floor, then reverse by contracting the quads. Hold something for balance if needed.', false, false),
('00000000-0000-0000-0000-000000000000', 'Wall Sit', 'Quads', ARRAY['Glutes'], 'Bodyweight', 'isolation', 'beginner', 'Stand with your back against a wall. Slide down until your thighs are parallel to the floor and your knees are at 90 degrees. Hold this position for time. Keep your back flat against the wall and do not place your hands on your thighs.', false, false),
('00000000-0000-0000-0000-000000000000', 'Goblet Squat', 'Quads', ARRAY['Glutes','Core'], 'Kettlebell', 'squat', 'beginner', 'Hold a kettlebell vertically at your chest with both hands cupping the bell. Squat down with feet slightly wider than shoulder-width, elbows tracking inside your knees at the bottom. Drive through your heels to stand. The front load promotes an upright torso.', false, false),
('00000000-0000-0000-0000-000000000000', 'Bulgarian Split Squat', 'Quads', ARRAY['Glutes','Hamstrings','Core'], 'Dumbbell', 'squat', 'intermediate', 'Stand about two feet in front of a bench. Place one foot behind you on the bench. Lower your rear knee toward the floor by bending your front knee, keeping your torso upright. Drive through your front heel to return. This is one of the most effective single-leg quad exercises.', false, false),

-- ============================================================
-- FULL BODY (13 exercises)
-- ============================================================
('00000000-0000-0000-0000-000000000000', 'Deadlift', 'Full Body', ARRAY['Back','Glutes','Hamstrings','Core'], 'Barbell', 'hinge', 'intermediate', 'Stand with feet hip-width and the bar over your mid-foot. Hinge at the hips and grip the bar just outside your legs. Brace your core hard, then drive through the floor to stand. Lock hips and knees out simultaneously at the top. Lower the bar with control by hinging back at the hips.', false, false),
('00000000-0000-0000-0000-000000000000', 'Burpee', 'Full Body', ARRAY['Chest','Shoulders','Core','Quads'], 'Bodyweight', 'compound', 'beginner', 'From standing, drop your hands to the floor and jump your feet back to a push-up position. Perform a push-up, then jump your feet back to your hands and explosively jump upward, reaching overhead. Land softly and immediately go into the next rep.', false, false),
('00000000-0000-0000-0000-000000000000', 'Power Clean', 'Full Body', ARRAY['Back','Shoulders','Glutes','Hamstrings','Core'], 'Barbell', 'compound', 'advanced', 'Start like a deadlift. Explosively extend your hips, knees, and ankles (the triple extension), then shrug and pull the bar up. As it reaches chest height, drop under it and catch in a front rack position with elbows high. Stand up to complete the lift. Requires coaching to learn safely.', false, false),
('00000000-0000-0000-0000-000000000000', 'Thruster', 'Full Body', ARRAY['Shoulders','Triceps','Glutes','Quads','Core'], 'Barbell', 'compound', 'intermediate', 'Hold a barbell in a front rack position. Perform a front squat, then as you drive up from the bottom, use the momentum to press the bar overhead to lockout in one fluid movement. Lower the bar back to the rack position and immediately squat again. Keep the core tight throughout.', false, false),
('00000000-0000-0000-0000-000000000000', 'Turkish Get-Up', 'Full Body', ARRAY['Shoulders','Core','Glutes','Hamstrings'], 'Kettlebell', 'compound', 'advanced', 'Lie on your back holding a kettlebell at arm''s length above you. Keep your eyes on the bell throughout. Roll to your elbow, then your hand, sweep your leg through to kneeling, then stand. Reverse all steps to return to the floor. Perform slowly — this is a movement skill as much as an exercise.', false, false),
('00000000-0000-0000-0000-000000000000', 'Kettlebell Swing', 'Full Body', ARRAY['Glutes','Hamstrings','Back','Core'], 'Kettlebell', 'hinge', 'intermediate', 'Stand with feet shoulder-width and the kettlebell on the floor in front of you. Hinge back at the hips, grip the bell, and hike it back between your legs. Explosively extend your hips to drive the bell forward and up to shoulder height. Let gravity bring it back and hinge immediately into the next rep.', false, false),
('00000000-0000-0000-0000-000000000000', 'Clean and Press', 'Full Body', ARRAY['Back','Shoulders','Triceps','Glutes','Hamstrings','Core'], 'Barbell', 'compound', 'advanced', 'Clean the barbell from the floor to a front rack position using a power clean. Without pausing, press the bar overhead to lockout. Lower the bar back to the rack, then to the floor. The combination of a pull and a push in one movement makes this a true full body exercise.', false, false),
('00000000-0000-0000-0000-000000000000', 'Bear Crawl', 'Full Body', ARRAY['Shoulders','Core','Quads'], 'Bodyweight', 'compound', 'beginner', 'Start on all fours with knees hovering just above the floor. Move opposite hand and foot forward simultaneously, keeping your back flat and hips low. Travel forward for the prescribed distance or time. Keep your core engaged and avoid letting your hips rise or rotate.', false, false),
('00000000-0000-0000-0000-000000000000', 'Man Maker', 'Full Body', ARRAY['Chest','Back','Shoulders','Biceps','Core','Quads'], 'Dumbbell', 'compound', 'advanced', 'Hold dumbbells in a push-up position. Perform a push-up, then row one dumbbell to your hip, then the other. Jump or step your feet to your hands. Clean the dumbbells to your shoulders and press overhead. Lower and repeat. Each rep is a complete full body movement.', false, false),
('00000000-0000-0000-0000-000000000000', 'Farmers Carry', 'Full Body', ARRAY['Core','Traps','Forearms'], 'Dumbbell', 'carry', 'beginner', 'Pick up a heavy dumbbell or kettlebell in each hand and walk for the prescribed distance or time. Keep your shoulders packed, chest tall, and core braced. Take controlled steps and do not let the weight pull you to one side. Set down under control at the end.', false, false),
('00000000-0000-0000-0000-000000000000', 'Battle Ropes', 'Full Body', ARRAY['Shoulders','Core','Biceps'], 'Battle Ropes', 'compound', 'intermediate', 'Anchor the ropes at a fixed point. Hold one end in each hand. Create waves by alternating or simultaneous arm movements — slams, circles, or lateral waves. Keep your hips low and core braced. Work continuously for the prescribed time interval.', false, false),
('00000000-0000-0000-0000-000000000000', 'Sled Push', 'Full Body', ARRAY['Quads','Glutes','Hamstrings','Core'], 'Sled', 'compound', 'intermediate', 'Load the sled with the desired weight. Place both hands on the poles and lean into the sled at roughly 45 degrees. Drive with short, powerful steps, pushing through the balls of your feet. Keep your arms straight and your core braced. Push for the prescribed distance.', false, false),
('00000000-0000-0000-0000-000000000000', 'Sled Pull', 'Full Body', ARRAY['Back','Hamstrings','Glutes','Core'], 'Sled', 'compound', 'intermediate', 'Attach a rope or strap to a loaded sled. Face the sled or walk away from it pulling hand-over-hand. Alternatively, face away and pull with a rope between your legs using a hip hinge. Both variations are low-impact and highly effective for posterior chain and conditioning work.', false, false),

-- ============================================================
-- CARDIO (13 exercises)
-- ============================================================
('00000000-0000-0000-0000-000000000000', 'Running (Treadmill)', 'Cardio', ARRAY[]::text[], 'Machine', 'cardio', 'beginner', 'Set the treadmill to your target speed and incline. Run with an upright posture, relaxed shoulders, and a midfoot strike. For steady-state work, maintain a conversational pace. For intervals, alternate between effort and recovery speeds. Do not hold the handrails.', false, false),
('00000000-0000-0000-0000-000000000000', 'Outdoor Run', 'Cardio', ARRAY[]::text[], 'Bodyweight', 'cardio', 'beginner', 'Run outdoors at your target pace. Focus on an upright posture, relaxed arms, and a cadence of roughly 170-180 steps per minute. Use GPS or a running app to track distance and pace. Vary terrain to engage different muscle groups and prevent overuse injuries.', false, false),
('00000000-0000-0000-0000-000000000000', 'Cycling (Stationary Bike)', 'Cardio', ARRAY['Quads','Hamstrings'], 'Machine', 'cardio', 'beginner', 'Adjust the seat so your knee has a slight bend at the bottom of the pedal stroke. Set resistance to a level that challenges you without compromising your cadence. Aim for 80-100 RPM for aerobic work or push higher resistance at lower cadence for strength-endurance.', false, false),
('00000000-0000-0000-0000-000000000000', 'Assault Bike', 'Cardio', ARRAY['Shoulders','Arms','Quads','Hamstrings'], 'Machine', 'cardio', 'intermediate', 'Sit on the assault bike and grip the moving handles. Push and pull simultaneously with your arms while pedalling. The fan creates increasing resistance as you go harder. Used most commonly for high-intensity intervals — push hard for 10-30 seconds, recover, repeat.', false, false),
('00000000-0000-0000-0000-000000000000', 'Rowing Machine', 'Cardio', ARRAY['Back','Hamstrings','Core','Shoulders'], 'Machine', 'cardio', 'intermediate', 'The rowing stroke has four phases: catch (knees bent, arms extended), drive (push with legs first, then lean back, then pull arms), finish (arms to lower chest, slight lean back), and recovery (arms extend, hinge forward, knees bend). Keep your core engaged throughout and drive primarily with your legs.', false, false),
('00000000-0000-0000-0000-000000000000', 'Stair Climber', 'Cardio', ARRAY['Glutes','Quads','Hamstrings','Calves'], 'Machine', 'cardio', 'beginner', 'Stand on the stair climber without leaning on the handrails — use them only for balance if needed. Set a pace that is challenging but sustainable. Step fully onto each step rather than just the ball of your foot. Maintain an upright posture and engage your core throughout.', false, false),
('00000000-0000-0000-0000-000000000000', 'Jump Rope', 'Cardio', ARRAY['Calves','Shoulders','Core'], 'Bodyweight', 'plyometric', 'beginner', 'Hold the rope handles with a relaxed grip. Turn the rope with small wrist circles, not big arm swings. Jump with both feet together, landing softly on the balls of your feet with a slight knee bend. Start with basic two-foot jumps and progress to alternating feet or double-unders.', false, false),
('00000000-0000-0000-0000-000000000000', 'Box Jump', 'Cardio', ARRAY['Quads','Glutes','Calves'], 'Bodyweight', 'plyometric', 'intermediate', 'Stand facing a box at a height you can jump safely. Hinge into a quarter squat, swing your arms, and explosively jump onto the box. Land with both feet flat, knees bent, and hips back. Stand fully upright. Step down — do not jump down. Reset before each rep.', false, false),
('00000000-0000-0000-0000-000000000000', 'Sprint Intervals', 'Cardio', ARRAY['Quads','Hamstrings','Glutes','Calves'], 'Bodyweight', 'cardio', 'intermediate', 'After a thorough warm-up, sprint at near-maximum effort for 10-30 seconds. Walk or jog for 60-120 seconds to recover. Repeat 6-10 times. Focus on driving your knees high and pushing hard through the ball of your foot. Sprint on a track, flat ground, or treadmill at a steep incline.', false, false),
('00000000-0000-0000-0000-000000000000', 'Elliptical', 'Cardio', ARRAY['Quads','Hamstrings','Glutes'], 'Machine', 'cardio', 'beginner', 'Set the desired resistance and incline. Push and pull the handles while maintaining a smooth, continuous stride. The elliptical is low-impact — ideal for active recovery or those with joint sensitivities. Increase incline to target the glutes and hamstrings more; decrease it to bias the quads.', false, false),
('00000000-0000-0000-0000-000000000000', 'Swimming', 'Cardio', ARRAY['Back','Shoulders','Core','Legs'], 'Bodyweight', 'cardio', 'intermediate', 'Choose a stroke appropriate for your level — freestyle, backstroke, breaststroke, or butterfly. Focus on maintaining a streamlined body position, efficient breathing, and consistent technique. Swimming is a full-body, zero-impact cardiovascular exercise that also builds upper body and core strength.', false, false),
('00000000-0000-0000-0000-000000000000', 'Ski Erg', 'Cardio', ARRAY['Back','Shoulders','Core','Triceps'], 'Machine', 'cardio', 'intermediate', 'Stand facing the ski erg with both hands gripping the handles overhead. Pull down and back in a double-pole skiing motion, hinging at the hips as the handles reach your sides. Let the handles rise to overhead as you stand back up. The movement is a full-body pull that heavily taxes the posterior chain and cardiovascular system.', false, false),
('00000000-0000-0000-0000-000000000000', 'Sled Drag', 'Cardio', ARRAY['Hamstrings','Glutes','Back'], 'Sled', 'carry', 'intermediate', 'Attach a harness or rope to a loaded sled. Face away from the sled and walk or run forward, dragging it behind you. Alternatively, face the sled and walk backward. The backward drag is particularly effective for the quads and is very low-impact. Use for conditioning finishers or active recovery work.', false, false);
